### ISSUE TITLE
Categorização de Playlists

### ISSUE THREAD

**Issue by Donads** [TreinaDev/stream-beta#48]
Eu, um administrador, desejo poder categorizar uma playlist, de forma que os vídeos/playlists de uma categoria oculta não sejam exibidos na plataforma.

**Comment by oohugo** [comment]
@paulo-castellan @daiaventureira 
Vocês estão nesta issues tem, algo feito ou pretendem terminar?
Se não eu gostaria de fazer, aproveito e coloco em video também

**Comment by daiaventureira** [comment]
> 

pode sim Hugo, senão vamos fazer amanhã. Mas se vc quiser trabalhar nessa pode sim
